### ISSUE TITLE
Crash with big file even with xml update

### ISSUE THREAD

**Issue by marvin-SL** [cyph/cordova-plugin-chooser#7]
Crash with big files.
Here's my config.xml https://pastebin.com/3Bp6UyrA

any advice ?

**Comment by yuankunluo** [comment]
soem problem hiere with cordova 7.1.4

**Comment by buu700** [comment]
Hey, sorry about the delay! I thought I'd have time to go through the issues collected here and in the Ionic repo by now, but should have time to look into it early next month. In the meantime, in case I can spot anything obviously wrong, would you be able to reupload the config from the expired pastebin?

**Comment by yuankunluo** [comment]
Hi @buu700 , 

The problem is that the getFile() will not be resolved or reject.

Our mate wideLandscapt has made a fork,

[wideLandscap's repo](https://github.com/wideLandscape/cordova-plugin-chooser

In his repo, he changed the signature of the getFile() method to:

`
  getFile(onSuccess: any, onError: any, accept?: string): undefined;
`

I am working on my Ionic4 project. In my Ionic4 Project the code works well like this.

`
const onSuccess = (data)=>{
      console.log(data);
    };

    const onError = (error)=>{
      console.error(error);
    }

    this.chooser.getFile(onSuccess, onError,"image/jpeg");
`

> I needed a chooser plugin so I decided to give this one a try (since it supports both android and iOS), but ran into the same issue. The root cause of the problem is that the getFile method returns a promise and the plugin is decorated wrong and assumes (regular) callback (ie. success/error) functions are used.
@chancezeus 

I hope this information helped. Be chill and merry Christmas my brother.
